#!/bin/bash

set -eu

G='\033[0;32m'
NC='\033[0m'
SCRIPT="$(readlink -f "$0")"
SCRIPTPATH=`dirname "$SCRIPT"`

# Color
printf "${G}"

src=( $(awk '{print $1}' "$SCRIPTPATH/mapper") )
dest=( $(awk '{print $2}' "$SCRIPTPATH/mapper") )
folders=( $(awk '{print $3}' "$SCRIPTPATH/mapper" | sed '/^$/d') )

#############################
# Create config dirs
#############################

for i in "${folders[@]}"; do
    mkdir -pv "$(eval echo $i)"
done

#############################
# Create symlink
#############################

if [[ "${#src[@]}" != "${#dest[@]}" ]]; then
    echo 'Fatal: Mismatch!'
    exit 1
else
    for ((i = 0; i < "${#src[@]}"; ++i)); do
        rm -rf "$(eval echo ${dest[$i]})"
        DEST="$(eval echo ${dest[$i]})"
        if [ -f "$DEST" ]; then
            rm -rf "$DEST"
        fi
        ln -sv "$SCRIPTPATH/$(eval echo ${src[$i]})" "$DEST"
    done
fi

printf "${NC}"

NVIMPLUGFILE=~/.local/share/nvim/site/autoload/plug.vim
if [ ! -e "$NVIMPLUGFILE" ]; then
    curl -fLo "$NVIMPLUGFILE" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +PlugInstall +qall
