#!/bin/bash

set -eu

G='\033[0;32m'
NC='\033[0m'
SCRIPT="$(readlink -f "$0")"
SCRIPTPATH=`dirname "$SCRIPT"`

read -p 'Do you want to backup packages list? {y/n} ' -i 'y' -e backup
if [ "$backup" == 'y' ]; then
    printf "${G}pacman -Qeq | grep -v \"\$(pacman -Qqm)\" > $SCRIPTPATH/installed.txt\n"
    if [ -n "$(pacman -Qqm)" ]; then
        pacman -Qeq | grep -v "$(pacman -Qqm)" > "$SCRIPTPATH/installed.txt"
    else
        pacman -Qeq > "$SCRIPTPATH/installed.txt"
    fi
    printf "pacman -Qqm > $SCRIPTPATH/aurinstalled.txt${NC}\n"
    (pacman -Qqm > "$SCRIPTPATH/aurinstalled.txt" || true)
fi

read -p 'Do you want to sync packages? {y/n} ' -i 'n' -e init
if [ "$init" == 'y' ]; then
    sudo pacman -S --needed - < installed.txt
fi

declare -a builds=("dwm" "dwmstatus" "st")
for i in "${builds[@]}"
do
    make clean -C "$i"
    make -C "$i"
    make install -C "$i"
done

# Oh my zsh
[ -d "$HOME/.oh-my-zsh" ] || sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

src=( $(awk '{print $1}' "$SCRIPTPATH/mapper") )
dest=( $(awk '{print $2}' "$SCRIPTPATH/mapper") )
folders=( $(awk '{print $3}' "$SCRIPTPATH/mapper" | sed '/^$/d') )

#############################
# Create config dirs
#############################

for i in "${folders[@]}"; do
    mkdir -pv "$(eval echo $i)"
done

#############################
# Create symlink
#############################

if [[ "${#src[@]}" != "${#dest[@]}" ]]; then
    echo 'Fatal: Mismatch!'
    exit 1
else
    for ((i = 0; i < "${#src[@]}"; ++i)); do
        rm -rf "$(eval echo ${dest[$i]})"
        DEST="$(eval echo ${dest[$i]})"
        if [ -f "$DEST" ]; then
            rm -rf "$DEST"
        fi
        ln -sv "$SCRIPTPATH/$(eval echo ${src[$i]})" "$DEST"
    done
fi

NVIMPLUGFILE=~/.local/share/nvim/site/autoload/plug.vim
if [ ! -e "$NVIMPLUGFILE" ]; then
    curl -fLo "$NVIMPLUGFILE" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +PlugInstall +qall
